# Generated by Django 5.0.7 on 2024-07-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_transactions', '0002_subaccount_family_account_alter_subaccount_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subaccount',
            name='balance',
            field=models.DecimalField(db_comment='The balance amount of the account, this is updatable only through a transaction.', decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='subaccount',
            name='family_account',
            field=models.ForeignKey(db_comment='The family account this sub account belongs and withdraws from', on_delete=django.db.models.deletion.CASCADE, related_name='sub_accounts', to='accounts_transactions.familyaccount'),
        ),
    ]
