# Generated by Django 5.0.7 on 2024-07-22 23:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="familyaccount",
            table="family_accounts",
        ),
        migrations.AlterModelTable(
            name="fundrequest",
            table="fund_requests",
        ),
        migrations.AlterModelTable(
            name="subaccount",
            table="sub_accounts",
        ),
    ]
