# Generated by Django 5.0.7 on 2024-08-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="familyaccount",
            name="name",
            field=models.CharField(db_index=True, max_length=100),
        ),
    ]
