# Generated by Django 5.0.7 on 2024-07-25 15:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        db_comment="The transaction amount",
                        decimal_places=2,
                        max_digits=10,
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        db_comment="The user who made the transaction"
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("savings", "Savings"),
                            ("withdrawal", "Withdrawal"),
                            ("investment", "Investment"),
                            ("airtime_top_up", "Airtime Top Up"),
                            ("bill_payment", "Bill Payment"),
                            ("transfers", "Transfers"),
                            ("fund_request", "Fund Request"),
                        ],
                        db_comment="The type of the transaction",
                        max_length=50,
                    ),
                ),
                (
                    "transaction_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("failed", "Failed"),
                            ("successful", "Successful"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_comment="The status of the transaction",
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_direction",
                    models.CharField(
                        choices=[
                            (
                                "sub_account_to_sub_account",
                                "Sub Account to Sub Account",
                            ),
                            (
                                "sub_account_to_family_account",
                                "Sub Account to Family Account",
                            ),
                            (
                                "family_account_to_sub_account",
                                "Family Account to Sub Account",
                            ),
                            (
                                "family_account_to_family_account",
                                "Family Account to Family Account",
                            ),
                            ("bank_to_sub_account", "Bank to Sub Account"),
                            ("sub_account_to_bank", "Sub Account to Bank"),
                            (
                                "bank_to_family_account",
                                "Bank to Family Account",
                            ),
                            (
                                "family_account_to_bank",
                                "Family Account to Bank",
                            ),
                            (
                                "mobile_wallet_to_family_account",
                                "Mobile Wallet to Family Account",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "details",
                    models.TextField(db_comment="Transaction details"),
                ),
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "family_destination_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_transactions",
                        to="accounts.familyaccount",
                    ),
                ),
                (
                    "family_source_account",
                    models.ForeignKey(
                        db_comment="The source account",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_transactions",
                        to="accounts.familyaccount",
                    ),
                ),
                (
                    "fund_request_id",
                    models.ForeignKey(
                        db_comment="The fund request that this transaction "
                        "belongs to",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="accounts.fundrequest",
                    ),
                ),
                (
                    "sub_destination_account",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="destination_transactions",
                        to="accounts.subaccount",
                    ),
                ),
                (
                    "sub_source_account",
                    models.ForeignKey(
                        db_comment="The source account",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="source_transactions",
                        to="accounts.subaccount",
                    ),
                ),
            ],
            options={
                "db_table": "transactions",
                "ordering": ["-created_at", "-updated_at"],
            },
        ),
    ]
