# Generated by Django 5.0.7 on 2024-07-25 15:38

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FamilyGroup",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(editable=False)),
                ("updated_at", models.DateTimeField(editable=False)),
                (
                    "owner_id",
                    models.UUIDField(
                        db_comment="The ID of the user who created the "
                        "family group, this person is also the "
                        "owner of the family group.",
                        db_index=True,
                    ),
                ),
                (
                    "is_default",
                    models.BooleanField(
                        blank=True,
                        db_comment="Indicates if the family group is the "
                        "default group for the user. Only one "
                        "family group can be the default group.It "
                        "is recommended to assign users to a "
                        "default group when they first join the "
                        "family.",
                        default=False,
                    ),
                ),
            ],
            options={
                "db_table": "family_groups",
                "ordering": ["-created_at"],
                "unique_together": {("name", "owner_id")},
            },
        ),
        migrations.CreateModel(
            name="FamilyMembership",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "user_id",
                    models.UUIDField(
                        db_comment="The ID of the user joining the family "
                        "group"
                    ),
                ),
                ("joined_at", models.DateTimeField(auto_now_add=True)),
                (
                    "family_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="family_memberships.familygroup",
                    ),
                ),
            ],
            options={
                "db_table": "family_memberships",
                "unique_together": {("user_id", "family_group")},
            },
        ),
    ]
