# Generated by Django 5.0.7 on 2024-07-23 05:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FamilyGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(db_comment='The name of the family group', max_length=255)),
                ('description', models.TextField(blank=True, db_comment='A brief description of the family group', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_comment='The date and time when the family group was created')),
                ('updated_at', models.DateTimeField(auto_now=True, db_comment='The date and time when the family group was last updated')),
            ],
            options={
                'verbose_name': 'Family Group',
                'verbose_name_plural': 'Family Groups',
                'db_table': 'family_group',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('member_name', models.CharField(db_comment='The name of the member', max_length=255)),
                ('email', models.EmailField(db_comment='The email address of the member', max_length=254)),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('member', 'Member')], db_comment='The role of the member within the family group', default='member', max_length=255)),
                ('joined_at', models.DateTimeField(auto_now_add=True, db_comment='The date and time when the member joined the family group')),
                ('family_group', models.ForeignKey(db_comment='The family group this membership belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to='family_memberships.familygroup')),
            ],
            options={
                'verbose_name': 'Membership',
                'verbose_name_plural': 'Memberships',
                'db_table': 'membership',
                'ordering': ['family_group', 'member_name'],
                'unique_together': {('family_group', 'email')},
            },
        ),
    ]
