# Generated by Django 5.0.7 on 2024-07-22 20:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_memberships', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='familygroup',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='email',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='member_name',
        ),
        migrations.RemoveField(
            model_name='membership',
            name='role',
        ),
        migrations.AddField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='memberships', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='familygroup',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='familygroup',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
