# Generated by Django 5.0.7 on 2024-07-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_memberships', '0002_remove_familygroup_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='familygroup',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
