# Generated by Django 5.0.7 on 2024-07-23 07:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_memberships', '0003_familygroup_updated_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='membership',
            old_name='id',
            new_name='membership_id',
        ),
        migrations.AddField(
            model_name='familygroup',
            name='owner_id',
            field=models.UUIDField(default=uuid.uuid4),
        ),
        migrations.AlterField(
            model_name='familygroup',
            name='description',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='familygroup',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='membership',
            name='family_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='family_memberships.familygroup'),
        ),
        migrations.AlterField(
            model_name='membership',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
