# Generated by Django 5.0.7 on 2024-07-23 17:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family_memberships', '0006_alter_membership_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Membership',
            new_name='FamilyMembership',
        ),
    ]
